### ISSUE TITLE
Add Feature to Put Environment Variable in YAML Config

### ISSUE THREAD

**Issue by hadihammurabi** [gowok/gowok#6]
example:
```yaml
app:
  web:
    enabled: true
    host: $HOST
```

$HOST value should come from env vars.
